# Generated by Django 2.1.4 on 2019-06-18 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='update_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
